spring:
  application:
    name: usersvc

server:
  port: 9001
  servlet:
    context-path: /userserver

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: @eureka.client.serviceUrl.defaultZone@
    registry-fetch-interval-seconds: 5
  instance:
      prefer-ip-address: true
      metadata-map.management.context-path: ${server.servlet.context-path}/actuator
